import { parseAbi } from "viem";

export const pactComputeMarketAbi = parseAbi([
  "function paymentToken() view returns (address)",
  "function nextRequestId() view returns (uint256)",
  "function totalEscrowed() view returns (uint256)",
  "function walletToDidHash(address) view returns (bytes32)",
  "function didHashToWallet(bytes32) view returns (address)",
  "function allowedProvider(address,address) view returns (bool)",
  "function getRequest(uint256) view returns ((address buyer,address provider,uint256 maxBudget,uint256 agreedPrice,uint64 quoteDeadline,uint64 workDuration,uint64 workDeadline,uint64 submittedAt,uint64 reviewPeriod,uint32 maxLatencyMs,bytes32 metadataHash,bytes32 requirementsHash,bytes32 expectedOutputHash,bytes32 providerDidHash,bytes32 acceptedQuoteHash,bytes32 resultHash,bytes32 outputHash,bytes32 attestationHash,uint8 requiredProof,uint8 status,bool rated))",
  "function getProviderStats(address) view returns ((bytes32 didHash,uint64 completedRequests,uint64 ratingCount,uint256 totalEarned,uint256 ratingSum,uint256 minimumPrice,uint32 capacity,bool active))",
  "function getBudgetPolicy(address) view returns ((uint256 maxPerRequest,uint256 dailyLimit,uint256 spentToday,uint64 day,bool allowlistOnly))",
  "function registerProvider(string displayName,string did,string[] modelFamilies,string hardwareClass,string region,uint256 minimumPrice,uint32 capacity)",
  "function updateProviderProfile(string displayName,string did,string[] modelFamilies,string hardwareClass,string region,uint256 minimumPrice,uint32 capacity,bool active)",
  "function setBudgetPolicy(uint256 maxPerRequest,uint256 dailyLimit,bool allowlistOnly)",
  "function setAllowedProvider(address provider,bool allowed)",
  "function createComputeRequest(uint256 maxBudget,uint64 quoteDeadline,uint64 workDuration,uint64 reviewPeriod,uint32 maxLatencyMs,bytes32 requirementsHash,bytes32 expectedOutputHash,uint8 requiredProof,string modelRef,string workload,string region,bool confidential) returns (uint256)",
  "function cancelOpenRequest(uint256 requestId)",
  "function selectProvider(uint256 requestId,address provider,bytes32 providerDidHash,uint256 agreedPrice,bytes32 quoteHash)",
  "function submitComputeResult(uint256 requestId,bytes32 resultHash,bytes32 outputHash,bytes32 attestationHash)",
  "function acceptComputeResult(uint256 requestId)",
  "function claimAfterReviewPeriod(uint256 requestId)",
  "function refundExpiredRequest(uint256 requestId)",
  "function abandonRequest(uint256 requestId)",
  "function rateProvider(uint256 requestId,uint8 rating)",
  "event ProviderRegistered(address indexed provider,bytes32 indexed didHash,string displayName,string did,string[] modelFamilies,string hardwareClass,string region,uint256 minimumPrice,uint32 capacity)",
  "event ProviderProfileUpdated(address indexed provider,bytes32 indexed didHash,string displayName,string did,string[] modelFamilies,string hardwareClass,string region,uint256 minimumPrice,uint32 capacity,bool active)",
  "event BudgetPolicyUpdated(address indexed buyer,uint256 maxPerRequest,uint256 dailyLimit,bool allowlistOnly)",
  "event ProviderPermissionUpdated(address indexed buyer,address indexed provider,bool allowed)",
  "event ComputeRequestCreated(uint256 indexed requestId,address indexed buyer,uint256 maxBudget,uint64 quoteDeadline,uint64 workDuration,uint64 reviewPeriod,uint32 maxLatencyMs,bytes32 metadataHash,bytes32 requirementsHash,bytes32 expectedOutputHash,uint8 requiredProof,string modelRef,string workload,string region)",
  "event ComputeRequestCancelled(uint256 indexed requestId,address indexed buyer,uint256 refund)",
  "event ProviderSelected(uint256 indexed requestId,address indexed provider,bytes32 indexed providerDidHash,uint256 agreedPrice,bytes32 quoteHash,uint64 workDeadline,uint256 buyerRefund)",
  "event ComputeResultSubmitted(uint256 indexed requestId,address indexed provider,bytes32 resultHash,bytes32 outputHash,bytes32 attestationHash,uint8 proofLevel)",
  "event ComputeRequestCompleted(uint256 indexed requestId,address indexed provider,uint256 payment)",
  "event ComputeRequestRefunded(uint256 indexed requestId,address indexed buyer,uint256 refund)",
  "event ComputeRequestAbandoned(uint256 indexed requestId,address indexed provider,uint256 refund)",
  "event ProviderRated(uint256 indexed requestId,address indexed provider,uint8 rating)",
]);
